# Generated by Django 4.2.5 on 2023-09-12 06:37

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bovinopublication_multimediavideo_multimediaimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ganaderia', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bovinopublication',
            name='categoria',
            field=models.CharField(choices=[('Ganado Carne', 'Ganado Carne'), ('Ganado Lechero', 'Ganado Lechero')], default='Ganado Carne', max_length=15),
        ),
        migrations.AddField(
            model_name='bovinopublication',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vendido', 'Vendido')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='bovinopublication',
            name='race',
            field=models.CharField(choices=[('Cebú', 'Cebú'), ('Simmental', 'Simmental'), ('Pardo Suizo', 'Pardo Suizo'), ('Jersey', 'Jersey'), ('Criollo', 'Criollo'), ('otro', 'otro')], default='otro', max_length=25),
        ),
        migrations.AlterField(
            model_name='bovinopublication',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Hembra', max_length=7),
        ),
        migrations.AlterField(
            model_name='multimediaimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/vendetuvaca/publicacion/'),
        ),
        migrations.AlterField(
            model_name='multimediavideo',
            name='video',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='images/vendetuvaca/videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGanaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/vendetuvaca/profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ganado', to='app.ganaderia')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaCertificadoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/vendetuvaca/Inscripcion/')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incripcion', to='app.bovinopublication')),
            ],
        ),
        migrations.AddField(
            model_name='ganaderia',
            name='user_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userinformation'),
        ),
        migrations.AddField(
            model_name='bovinopublication',
            name='ganaderia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ganaderia', to='app.ganaderia'),
        ),
    ]
