# Generated by Django 4.2.5 on 2023-09-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ganaderia_bovinopublication_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='plan_precios',
            field=models.CharField(blank=True, choices=[('Gratuito', 'Gratuito'), ('Vip', 'Vip'), ('Gold', 'Gold')], default=None, max_length=8, null=True),
        ),
    ]
