# Generated by Django 4.2.5 on 2023-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinformation_plan_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='is_verificado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
