# Generated by Django 4.2.5 on 2023-09-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userinformation_is_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cedula',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
