# Generated by Django 4.2.5 on 2023-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_plan_remove_userinformation_plan_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='plan_precios',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
