# Generated by Django 4.2.3 on 2023-10-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userinformation_plan_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovinopublication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
